version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
    security-updates-only: true
    open-pull-requests-limit: 10
    reviewers:
      - "jcequispe"
    commit-message:
      prefix: "security"
      include: "scope"
